### ISSUE TITLE
build.sh fails when uninstalling cybox

### ISSUE THREAD

**Issue by jamfwright** [harvard-itsecurity/docker-misp#30]
The console message is:

Step 33/41 : RUN sudo pip3 uninstall -y cybox
 ---> Running in f5d9b7225c74
Uninstalling cybox-2.1.0.18.dev0:
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/usr/local/lib/python3.6/dist-packages/cybox-2.1.0.18.dev0-py3.6.egg' -> '/tmp/pip-uninstall-tvvoudsu/usr/local/lib/python3.6/dist-packages/cybox-2.1.0.18.dev0-py3.6.egg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/uninstall.py", line 68, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 661, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_uninstall.py", line 219, in remove
    renames(path, new_path)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/misc.py", line 273, in renames
    shutil.move(old, new)
  File "/usr/lib/python3.6/shutil.py", line 556, in move
    rmtree(src)
  File "/usr/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.6/shutil.py", line 422, in _rmtree_safe_fd
    onerror(os.rmdir, fullname, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 420, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=topfd)
OSError: [Errno 39] Directory not empty: 'EGG-INFO'
Removing intermediate container f5d9b7225c74
The command '/bin/sh -c sudo pip3 uninstall -y cybox' returned a non-zero code: 2

**Comment by ventz** [comment]
@jamfwright I believe you are running into something non-misp (specifically, docker) related.

Can you provide:
```
% docker version
```

Make sure you are on:
```
Version:      18.03.1-ce
```

Once your version matches the above, if you are still getting the error, please try the following:

1.) remove the current image:
```
docker rmi harvarditsecurity/misp
```
2.) on your docker host, go into /tmp and clone the github repo there
3.) make sure your -v volume is on the same filesystem as your /tmp (vs different disk, or NFS)
4.) re-run the build from there

Just to eliminate the image itself, I built it on 3 different systems (Ubuntu 16.04 LTS running docker 18.03.1-ce, Ubuntu 18.04 LTS running 18.03.1-ce, and a Mac 10.13.6) without any issues.

**Comment by ventz** [comment]
Closing due to inactivity - assuming client side env/issue.
Please feel free to re-open if you/anyone else runs into this.
