### ISSUE TITLE
python-meac installation is failing

### ISSUE THREAD

**Issue by pettai** [harvard-itsecurity/docker-misp#42]
Not this projects fault, but I noted that a new installation of docker-misp fails at installing python-meac
```
 ---> Running in 29d6a12f7cdf
Processing /var/www/MISP/app/files/scripts/python-maec
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-bpzbsucp/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-bpzbsucp/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-req-build-bpzbsucp/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-bpzbsucp/setup.py", line 54, in <module>
        long_description=get_long_description(),
      File "/tmp/pip-req-build-bpzbsucp/setup.py", line 27, in get_long_description
        return f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 141: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Removing intermediate container 29d6a12f7cdf
The command '/bin/sh -c sudo pip3 install .' returned a non-zero code: 1
```

**Comment by ventz** [comment]
@ec4n6 Thanks for submitting the issue.

See here too:
https://github.com/MISP/docker-misp/issues/7

**Comment by emmanvg** [comment]
Fixed in v4.1.0.16

**Comment by ventz** [comment]
@emmanvg Great - thanks for the quick turn around time!

**Comment by pettai** [comment]
G8t! time to close this issue then
